### PR TITLE
DS in ES6

### PR DESCRIPTION
**Pull request by hemanth**
Rewrote files in ES6, hope you like it ;)

I had started [this](https://github.com/hemanth/es6-data-structures) couldn't complete so doing this PR instead.

### CODE REVIEW

**Comment by benoitvallon** [comment]
Hey @hemanth,

Thank you, this is awesome. Would you mind creating new files for es6 versions instead? I would like to keep the es5 and es6 separated. I think es5 is not dead yet and by doing this the project could also be a way to see and appreciate the new things introduced by es6. I am thinking of keeping the actual file name for es5 and adding new files with the suffixe .es6.js for the es6 versions like:

es5: `array.js`
es5: `array.es6.js`

Thanks again, that's an amazing job.

**Comment by arrowrowe** [comment]
Hi, I had started [some](https://github.com/arrowrowe/algorithms-node) as well, many of which were naively implemented. Don't know if it helps.

**Comment by benoitvallon** [comment]
If we are going to have the Data Structures part in es6, I thought it would be nice to have the Sorting Algorithms part as well so I started to add them in es6.

**Comment by benoitvallon** [comment]
@arrowrowe great resources, thanks

**Comment by hemanth** [comment]
@benoitvallon Sure, will work on it.

**Comment by hemanth** [comment]
@benoitvallon Done, would it make sense to organize ES5 and ES6 in separate dirs?

**Comment by benoitvallon** [comment]
@hemanth thanks for your work.
Yes probably, it would make the dir easier to compare. I will have a look at it today.

**Pull request merged**
